# Generated by Django 3.2.18 on 2023-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edueasyapp', '0003_auto_20230611_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='Password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sign',
            name='Repassword',
            field=models.CharField(max_length=60),
        ),
    ]
