# Generated by Django 3.2.18 on 2023-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edueasyapp', '0004_auto_20230611_0920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sign',
            table='Registered Users',
        ),
    ]
