# Generated by Django 3.2.18 on 2023-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edueasyapp', '0006_alter_sign_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='Repassword',
        ),
    ]
