# Generated by Django 3.2.18 on 2023-06-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edueasyapp', '0008_alter_sign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='Password',
            field=models.CharField(max_length=88),
        ),
    ]
