# Generated by Django 3.2.18 on 2023-06-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edueasyapp', '0010_alter_sign_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
